# Generated by Django 4.2.3 on 2023-07-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_alter_onlineshop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
